### ISSUE TITLE
ClassNotFoundException: com.jetbrains.completion.feature.FeatureManager PluginClassLoader

### ISSUE THREAD

**Issue by BorzdeG** [JetBrains/intellij-stats-collector#23]
IDE: IntelliJ IDEA (build #IU-183.5429.1, 11 Jan 2019 11:33) 
Plugin version: 183.5429.20

```
2019-01-22 14:37:37,332 [   4054]  ERROR - llij.ide.plugins.PluginManager - com.intellij.ide.plugins.PluginManager$StartupAbortedException: Fatal error initializing plugin com.intellij.stats.completion 
java.lang.RuntimeException: com.intellij.ide.plugins.PluginManager$StartupAbortedException: Fatal error initializing plugin com.intellij.stats.completion
	at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:215)
	at com.intellij.idea.IdeaApplication.lambda$initApplication$0(IdeaApplication.java:74)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:342)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: com.intellij.ide.plugins.PluginManager$StartupAbortedException: Fatal error initializing plugin com.intellij.stats.completion
	at com.intellij.ide.plugins.PluginManager.handleComponentError(PluginManager.java:253)
	at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.handleInitComponentError(PlatformComponentManagerImpl.java:43)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.registerComponents(ComponentManagerImpl.java:390)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:81)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:405)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:391)
	at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:208)
	... 16 more
Caused by: com.intellij.diagnostic.PluginException: com.jetbrains.completion.feature.FeatureManager PluginClassLoader[com.intellij.stats.completion, 183.5429.20] com.intellij.ide.plugins.cl.PluginClassLoader@2135fa2f [Plugin: com.intellij.stats.completion]
	... 23 more
Caused by: java.lang.ClassNotFoundException: com.jetbrains.completion.feature.FeatureManager PluginClassLoader[com.intellij.stats.completion, 183.5429.20] com.intellij.ide.plugins.cl.PluginClassLoader@2135fa2f
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:49)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.registerComponents(ComponentManagerImpl.java:371)
	... 20 more
```

**Comment by bibaev** [comment]
Incompatible versions were uploaded automatically. I've removed the plugin from the auto-uploading list. Broken updates should not appear again.
